### ISSUE TITLE
this.props.exp.notification error using Toast with Expo v20

### ISSUE THREAD

**Issue by acomito** [ant-design/ant-design-mobile#1738]
### Version
1.6.3

### Environment
expo 20, iphone

### Reproduction link
[https://github.com/acomito/expo20-antd-mobile-toast](https://github.com/acomito/expo20-antd-mobile-toast)

### Steps to reproduce
see repo: https://github.com/acomito/expo20-antd-mobile-toast

1. Load the app (run yarn command to download node_modules, don't use npm as later versions wont work with expo)

2. you should see no problems, go into App.js and uncomment the Toast function call in onClick. Save so expo reloads the app

3. app won't reload. Instead you'll see a this.props.exp.notification undefined error

### What is expected?
Expo should compile as normal, and button click should cause toast to fire. 

### What is actually happening?
Toast is causing expo to fail compiling.

---
 I think maybe this expo, but I'm not sure. I posted it here to let antd-mobile be aware of it.

**Comment by silentcloud** [comment]
@acomito check the antd-mobile expo demo （https://github.com/ant-design/ant-design-mobile#react-native-demo，be sure if it works correctly

**Comment by fengyibo** [comment]
https://github.com/ant-design/antd-mobile-samples/tree/master/rn-expo 
yarn && yarn ios got the same error

**Comment by acomito** [comment]
@silentcloud @fengyibo That is with expo sdk 17, I was using sdk 20, and an older version of antd-mobile. I'm fairly certain this worked for me with expo 19 and antd-mobile (maybe 1.5-ish). I updaed both expo and antd-mobile, then could get the app started because of this error.

**Comment by fengyibo** [comment]
I test Modal.alert,  got the same error.
and then i test other component used " import topView from 'rn-topview'; "
got the same error.

**Comment by Bedrock123** [comment]
I am getting the same error after upgrading to sdk 20. After deleting all instances of Toast from antd-mobile, the error went away.

**Comment by fengyibo** [comment]
I make log in rn-topview topView.js 
`  }(_react.Component), originRegisterComponent = _reactNative.AppRegistry.registerComponent;
_reactNative.AppRegistry.registerComponent = function (e, t) {
  var r = this, n = t();
  console.log(this.props);
  console.log(t.toString());
  return originRegisterComponent(e, function () {
    console.log(n)
    return function () {
      return _react2.default.createElement(_reactNative.View, {style: {flex: 1}}, _react2.default.createElement(n, r.props), _react2.default.createElement(TopView, null))
    }
  })`

props is {}

maybe topview overwrite registerComponent and lost props

without Toast props in App is prsent

**Comment by silentcloud** [comment]
Ok, thanks @fengyibo , I will check this.

**Comment by silentcloud** [comment]
@acomito @fengyibo this has been fixed in rn-topview@0.1.5, please `rm -rf node_modules && yarn`

**Comment by Bedrock123** [comment]
After running `rm -rf node_modules && yarn` the error is still there for me when importing in Toast from antd-mobile?

**Comment by silentcloud** [comment]
@Bedrock123 Be sure rn-topview is version 0.1.5 in your node_modules folder.
I have tested in @acomito's github example, everything is ok.

![image](https://user-images.githubusercontent.com/1698185/29800951-9c3a1518-8c9f-11e7-8fbf-4d7f55cf5f8f.png)

**Comment by acomito** [comment]
Thanks @silentcloud -- please feel free to close the issue.

**Comment by Bedrock123** [comment]
@silentcloud Yes you were right -just had to upgrade rn-topview. Thanks!
